-- MySQL Script generated by MySQL Workbench
-- Thu Jul 18 16:22:09 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gemodoc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gemodoc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gemodoc` DEFAULT CHARACTER SET utf8 ;
USE `gemodoc` ;

-- -----------------------------------------------------
-- Table `gemodoc`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gemodoc`.`usuario` (
  `login` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`login`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gemodoc`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gemodoc`.`admin` (
  `idadmin` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(255) NOT NULL,
  `usuario_login` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idadmin`, `usuario_login`),
  INDEX `fk_admin_usuario_idx` (`usuario_login` ASC)  ,
  CONSTRAINT `fk_admin_usuario`
    FOREIGN KEY (`usuario_login`)
    REFERENCES `gemodoc`.`usuario` (`login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gemodoc`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gemodoc`.`professor` (
  `idprofessor` INT NOT NULL AUTO_INCREMENT,
  `usuario_login` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idprofessor`, `usuario_login`),
  INDEX `fk_professor_usuario1_idx` (`usuario_login` ASC)  ,
  CONSTRAINT `fk_professor_usuario1`
    FOREIGN KEY (`usuario_login`)
    REFERENCES `gemodoc`.`usuario` (`login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gemodoc`.`responsavel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gemodoc`.`responsavel` (
  `idresponsavel` INT NOT NULL AUTO_INCREMENT,
  `usuario_login` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idresponsavel`, `usuario_login`),
  INDEX `fk_responsavel_usuario1_idx` (`usuario_login` ASC)  ,
  CONSTRAINT `fk_responsavel_usuario1`
    FOREIGN KEY (`usuario_login`)
    REFERENCES `gemodoc`.`usuario` (`login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gemodoc`.`turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gemodoc`.`turma` (
  `idturma` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idturma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gemodoc`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gemodoc`.`aluno` (
  `idaluno` INT NOT NULL AUTO_INCREMENT,
  `serie` INT NOT NULL,
  `ano_inicio` INT NOT NULL,
  `ano_fim` INT NULL,
  `usuario_login` VARCHAR(255) NOT NULL,
  `responsavel_idresponsavel` INT NOT NULL,
  `turma_idturma` INT NOT NULL,
  PRIMARY KEY (`idaluno`, `usuario_login`),
  INDEX `fk_aluno_usuario1_idx` (`usuario_login` ASC)  ,
  INDEX `fk_aluno_responsavel1_idx` (`responsavel_idresponsavel` ASC)  ,
  INDEX `fk_aluno_turma1_idx` (`turma_idturma` ASC)  ,
  CONSTRAINT `fk_aluno_usuario1`
    FOREIGN KEY (`usuario_login`)
    REFERENCES `gemodoc`.`usuario` (`login`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_responsavel1`
    FOREIGN KEY (`responsavel_idresponsavel`)
    REFERENCES `gemodoc`.`responsavel` (`idresponsavel`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_turma1`
    FOREIGN KEY (`turma_idturma`)
    REFERENCES `gemodoc`.`turma` (`idturma`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gemodoc`.`tipo_ocorrencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gemodoc`.`tipo_ocorrencia` (
  `idtipo_ocorrencia` INT NOT NULL AUTO_INCREMENT,
  `nivel` INT NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idtipo_ocorrencia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gemodoc`.`ocorrencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gemodoc`.`ocorrencia` (
  `idocorrencia` INT NOT NULL AUTO_INCREMENT,
  `data` DATETIME NOT NULL,
  `tipo_ocorrencia_idtipo_ocorrencia` INT NOT NULL,
  `professor_idprofessor` INT NOT NULL,
  `aluno_idaluno` INT NOT NULL,
  `cancelada` TINYINT NULL,
  PRIMARY KEY (`idocorrencia`),
  INDEX `fk_ocorrencia_tipo_ocorrencia1_idx` (`tipo_ocorrencia_idtipo_ocorrencia` ASC)  ,
  INDEX `fk_ocorrencia_professor1_idx` (`professor_idprofessor` ASC)  ,
  INDEX `fk_ocorrencia_aluno1_idx` (`aluno_idaluno` ASC)  ,
  CONSTRAINT `fk_ocorrencia_tipo_ocorrencia1`
    FOREIGN KEY (`tipo_ocorrencia_idtipo_ocorrencia`)
    REFERENCES `gemodoc`.`tipo_ocorrencia` (`idtipo_ocorrencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ocorrencia_professor1`
    FOREIGN KEY (`professor_idprofessor`)
    REFERENCES `gemodoc`.`professor` (`idprofessor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ocorrencia_aluno1`
    FOREIGN KEY (`aluno_idaluno`)
    REFERENCES `gemodoc`.`aluno` (`idaluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gemodoc`.`tipo_suspensao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gemodoc`.`tipo_suspensao` (
  `idtipo_suspensao` INT NOT NULL AUTO_INCREMENT,
  `nivel` INT NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idtipo_suspensao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gemodoc`.`suspensao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gemodoc`.`suspensao` (
  `idsuspensao` INT NOT NULL AUTO_INCREMENT,
  `data` DATETIME NOT NULL,
  `quant_dias` INT NOT NULL,
  `tipo_suspensao_idtipo_suspensao` INT NOT NULL,
  `admin_idadmin` INT NOT NULL,
  `aluno_idaluno` INT NOT NULL,
  PRIMARY KEY (`idsuspensao`),
  INDEX `fk_suspensao_tipo_suspensao1_idx` (`tipo_suspensao_idtipo_suspensao` ASC)  ,
  INDEX `fk_suspensao_admin1_idx` (`admin_idadmin` ASC)  ,
  INDEX `fk_suspensao_aluno1_idx` (`aluno_idaluno` ASC)  ,
  CONSTRAINT `fk_suspensao_tipo_suspensao1`
    FOREIGN KEY (`tipo_suspensao_idtipo_suspensao`)
    REFERENCES `gemodoc`.`tipo_suspensao` (`idtipo_suspensao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_suspensao_admin1`
    FOREIGN KEY (`admin_idadmin`)
    REFERENCES `gemodoc`.`admin` (`idadmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_suspensao_aluno1`
    FOREIGN KEY (`aluno_idaluno`)
    REFERENCES `gemodoc`.`aluno` (`idaluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gemodoc`.`tipo_saida_sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gemodoc`.`tipo_saida_sala` (
  `idtipo_saida_sala` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idtipo_saida_sala`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gemodoc`.`saida_sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gemodoc`.`saida_sala` (
  `idsaida_sala` INT NOT NULL AUTO_INCREMENT,
  `horário_aula` INT NOT NULL,
  `fazendo_prova` TINYINT NOT NULL,
  `tipo_saida_sala_idtipo_saida_sala` INT NOT NULL,
  `admin_idadmin` INT NOT NULL,
  `aluno_idaluno` INT NOT NULL,
  PRIMARY KEY (`idsaida_sala`),
  INDEX `fk_saida_sala_tipo_saida_sala1_idx` (`tipo_saida_sala_idtipo_saida_sala` ASC)  ,
  INDEX `fk_saida_sala_admin1_idx` (`admin_idadmin` ASC)  ,
  INDEX `fk_saida_sala_aluno1_idx` (`aluno_idaluno` ASC)  ,
  CONSTRAINT `fk_saida_sala_tipo_saida_sala1`
    FOREIGN KEY (`tipo_saida_sala_idtipo_saida_sala`)
    REFERENCES `gemodoc`.`tipo_saida_sala` (`idtipo_saida_sala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_saida_sala_admin1`
    FOREIGN KEY (`admin_idadmin`)
    REFERENCES `gemodoc`.`admin` (`idadmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_saida_sala_aluno1`
    FOREIGN KEY (`aluno_idaluno`)
    REFERENCES `gemodoc`.`aluno` (`idaluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gemodoc`.`adm_altera_oc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gemodoc`.`adm_altera_oc` (
  `admin_idadmin` INT NOT NULL,
  `ocorrencia_idocorrencia` INT NOT NULL,
  `data` DATETIME NOT NULL,
  `motivo` VARCHAR(255) NOT NULL,
  INDEX `fk_admin_has_ocorrencia_ocorrencia1_idx` (`ocorrencia_idocorrencia` ASC)  ,
  INDEX `fk_admin_has_ocorrencia_admin1_idx` (`admin_idadmin` ASC)  ,
  CONSTRAINT `fk_admin_has_ocorrencia_admin1`
    FOREIGN KEY (`admin_idadmin`)
    REFERENCES `gemodoc`.`admin` (`idadmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_admin_has_ocorrencia_ocorrencia1`
    FOREIGN KEY (`ocorrencia_idocorrencia`)
    REFERENCES `gemodoc`.`ocorrencia` (`idocorrencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
