service: dev-secret
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x

plugins:
  - serverless-offline

functions:
  create:
    handler: src/handlers/secret.create
    events:
      - httpApi:
          path: /secret
          method: post
          cors: true

  get:
    handler: src/handlers/secret.get
    events:
      - httpApi:
          path: /secret/{id}
          method: get
          cors: true

  draw:
    handler: src/handlers/secret.draw
    events:
      - httpApi:
          path: /secret/{id}/draw
          method: put
          cors: true

  createParticipant:
    handler: src/handlers/participants.create
    events:
      - httpApi:
          path: /secret/{id}/participants
          method: post
          cors: true

  deleteParticipant:
    handler: src/handlers/participants.delete
    events:
      - httpApi:
          path: /secret/{id}/participants/{participantID}
          method: delete
          cors: true

