/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

//import java.util.*;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Hugo Nathan
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        
        initComponents();
        
        try {

            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            SwingUtilities.updateComponentTreeUI(this);
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e) {

            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gerarData = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        campoTextoData.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        campoTextoData.setText("00/00/0000");

        gerarData.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        gerarData.setText("Gerar Data");
        gerarData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerarDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campoTextoData)
                    .addComponent(gerarData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(campoTextoData, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(gerarData)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void gerarDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerarDataActionPerformed
        // TODO add your handling code here:
        
        Random geraAle = new Random();
        
        Integer dia = null, mes, ano;
        
        do {
            
            ano = geraAle.nextInt(2005);
        }while(ano<1980);
        
        //ano=2001;
        
        do {
            
            mes = geraAle.nextInt(13);
        }while (mes == 0);
        
        //mes =2;
        
        if (mes == 4 || mes == 6 || mes == 9 || mes == 11) {
        
            do {
                
                dia = geraAle.nextInt(31);
            }while (dia == 0);
        }
        
        else if (mes == 2) {
            
            if (ano % 4 != 0) {
                
                // Não é bissexto
                
                do {

                    dia = geraAle.nextInt(29);
                }while (dia == 0);
            }
            
            else {
            
                if (ano % 100 != 0) {
                
                    do {

                        dia = geraAle.nextInt(30);
                    }while (dia == 0);
                    //}while (dia <27);
                }
                
                else {
                    
                    if (ano % 400 == 0) {
                        
                        do {

                            dia = geraAle.nextInt(30);
                        }while (dia == 0);   
                        //}while (dia <27);
                    }
                }
            }
        }
        
        else {
            
            do {
                
                dia = geraAle.nextInt(32);
            }while (dia == 0);
        
        }
        
        //System.out.println(dia+"/"+mes+"/"+ano);
        
        String strDia,strMes,strAno = ano.toString();
        
        if (dia < 10)
            strDia = "0"+dia.toString();
        else
            strDia = dia.toString();
        
        if (mes < 10)
            strMes = "0"+mes.toString();
        else
            strMes = mes.toString();
            
        campoTextoData.setText(strDia+"/"+strMes+"/"+strAno);
        
    }//GEN-LAST:event_gerarDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public final javax.swing.JTextField campoTextoData = new javax.swing.JTextField();
    private javax.swing.JButton gerarData;
    // End of variables declaration//GEN-END:variables
}
